# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WordNet-SenseKey
version:      1.03
version_from: lib/WordNet/SenseKey.pm
installdirs:  site
requires:
    WordNet::QueryData:            1.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
